android.useAndroidX=true
android.newDsl=false
sdk.dir=/Users/aditya/Library/Android/sdk
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx8g
org.gradle.java.home=C\:\\Program Files\\Android\\Android Studio\\jbr


# Flow Neuroengine
FLOW_NEURO_BASE_URL=https://api.flowneuroengine.com
FLOW_NEURO_API_KEY=dummy_key

org.gradle.java.installations.auto-detect=false
org.gradle.java.installations.paths=C\:\\Program Files\\Android\\Android Studio\\jbr

